
# Generated by /home/fdkit/GPL-AirCam-v1.2/openwrt/build_dir/host/cmake-2.8.4/bootstrap
# Default cmake settings.  These may be overridden any settings below.
SET (CMAKE_INSTALL_PREFIX "/home/fdkit/GPL-AirCam-v1.2/openwrt/staging_dir/host" CACHE PATH "Install path prefix, prepended onto install directories." FORCE)
SET (CMAKE_DOC_DIR "/doc/cmake-2.8" CACHE PATH "Install location for documentation (relative to prefix)." FORCE)
SET (CMAKE_MAN_DIR "/man" CACHE PATH "Install location for man pages (relative to prefix)." FORCE)
SET (CMAKE_DATA_DIR "/share/cmake-2.8" CACHE PATH "Install location for data (relative to prefix)." FORCE)

