# All makefile fragments assume that $(srcdir) points to the gcc
# directory, not the language subdir
srcdir = /home/fdkit/GPL-AirCam-v1.2/openwrt/build_dir/toolchain-arm_v5te_gcc-linaro_uClibc-0.9.32_eabi/gcc-linaro-4.5-2011.02-0/gcc
-include ./gcc-interface/Makefile
-include ../gcc-interface/Makefile
